workflows:
  pomdoro-workflow:
    name: Pomodoro Pipeline
    scripts:
      - name: CICD Started
        script: echo "Welcome to CI/CD set up"
      - name: Build Pomodoro
        script: xcodebuild build -project "Pomodoro.xcodeproj" -scheme "Pomodoro" CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO Code_SIGNING-ALLOWED=NO
    publishing:
        email:
          recipients:
            - ollmann.ph@gmail.com
